export enum AuthErrorCodes {
  NOTFOUND = 'NOT_FOUND',
  INVALID_PWD = 'INVALID_PASSWORD',
  VALIDATION = 'INVALID_VALUE',
  INVALID_TOKEN = 'INVALID_TOKEN'
}

export enum ServiceErrorCodes {
  JWT_INVALID_TOKEN = 'JWT_INVALID_TOKEN',
  JWT_INVALID_TOKEN_SIGNATURE = 'JWT_INVALID_TOKEN_SIGNATURE',
  INTERNAL = 'INTERNAL ERROR',
  ACCESS_DENIED = 'THIE REPOSITORY HAS PRIVATE ACCESS',
  GITHUB_INVALID_PATH = 'REPOSITORY PATH IS INVALID',
  GITHUB_PATH_REQUIRED = 'GITHUB PATH IS REQUIRED',
  OBSCURE_ERROR = 'SOMETHING WENT WRONG'
}

export enum ProjectErrors {
  INVALID_ID = 'INVALID PROJECT ID',
  NOT_FOUD = 'PROJECT_NOT_FOUND',
  FORBIDDEN= 'USER_HAS_NO_PERMISSION'
}

export enum ProjectDeleteErrors {
  NOTFOUND= 'PROJECT_NOT_FOUND',
  FORBIDDEN= 'USER_HAS_NO_PERMISSION'
}

export enum UserErrorCodes {
  EXISTED = 'EXISTED_EMAIL',
  VALIDATION = 'INVALID_VALUE',
  NOTFOUND = 'EMAIL_NOT_FOUND'
}

export type ErrorCodes =
  AuthErrorCodes |
  ServiceErrorCodes |
  UserErrorCodes |
  ProjectErrors | 
  ProjectDeleteErrors;